### ISSUE TITLE
update_gh_pages uses default (githubactions bot.) ignoring author_name / author_email secrets

### ISSUE THREAD

**Issue by nickynicolson** [ObsidianPublisher/actions#11]
Secrets for author_email and author_name don;t appear to be used in the `update-gh-pages` part of https://github.com/ObsidianPublisher/actions/blob/main/.github/workflows/maintenance.yml, causing an error.
https://github.com/nickynicolson/bison/actions/runs/6774343479/job/18411200324
Do these need to be specified earlier, when the checkout is made?https://github.com/ObsidianPublisher/actions/blob/4b532421a5ab77e5242e415fdd20723d77035942/.github/workflows/maintenance.yml#L113

**Comment by Mara-Li** [comment]
As the secrets set in the definition of the file, you needs to set it as a secrets, like you done with `GH_PAT`

**Comment by nickynicolson** [comment]
As explained - I have set the relevant secrets (AUTHOR_EMAIL and AUTHOR_NAME), but they are not being used by the push action as shown in the attached log, instead the default "github-actions[bot]" values are used - relevant snippet from the logs below:
```
Run actions-js/push@master
  with:
    github_token: ***
    author_email: github-actions[bot]@users.noreply.github.com
    author_name: github-actions[bot]
    branch: main
    amend: false
    directory: .
```

**Comment by Mara-Li** [comment]
But… You didn't set them in the Github actions… Obviously they can't use it !

**Comment by Mara-Li** [comment]
You need to update it like that:
```yml
name: Repository maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    uses: ObsidianPublisher/actions/.github/workflows/maintenance.yml@main
    with:
      CLEAN: true
      DRY_RUN: false
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
      AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
```
