### ISSUE TITLE
"EXCLUDED_FILES" in update.yml does not work

### ISSUE THREAD

**Issue by UtilityWorlds** [ObsidianPublisher/actions#5]
This is my update.yml.
```
name: Get latest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: true
      EXCLUDED-FILES: 'docs/tags.md'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

When I run it, the auto-update process still override both the files "tags.md" and "overrides/partials/comments.html"

Maybe it's due to the file update.yml running the command: "unzip release" 2 times.
<img width="347" alt="image" src="https://github.com/ObsidianPublisher/actions/assets/126215834/aa29b612-8ca4-4be9-8908-6b59de56aca5">
